{% extends 'main/base.html' %}

{% block head %}
    {{ block.super }}
    <script src="{% url main:api %}"></script>
{% endblock %}

{% block body %}
    <h2>#1 Test MainApi</h2>
    <a href="{% url main:index %}">back</a>
    <div>
        <pre>
        #rpc.py
        from utils.rpc import RpcRouter
        from utils.rpc import Error, Msg
        
        class MainApiClass(object):
            
            def func1(self, val, d=123, *args, **kwargs):
                return Msg(u'func1')
            
            def func2(self, user):
                return {}
                
        router = RpcRouter('main:router', {
            'MainApi': MainApiClass()
        })                
        </pre>
        <p>
            Set arguments separated by "," to send them with RPC. <br/>
            Callback is optional. Here it just to display response. <br/>
            You can also pass scope for callback after "callback".
         </p>        
        <div class="test">
            <p class="code"></p>
            <input type="text" value="1, 2, 3, 4, 5"></input>
            <button method_name="MainApi.func1">MainApi.func1</button>
            <p class="description">
                "val" is required argument.<br/>
                "d" is optional with default value.<br/>
                And you can pass any amount of arguments.<br/>
                "kwargs" contain "request.user" object. You should use it if
                you have optional arguments. Maybe I'll fix it later, but it
                good enough for Python.<br/><br/>
                "Msg" it is just dictionary {"msg": value}.<br/>
                "Error" is {"error": value}.<br/>
                I use them just have same response format for all methods and
                maybe add some more logic and don't change a lot of code<br/><br/>
                If you pass ecorect number of arguments, func1 will never be called.
                Router just return exception that can be catched this way:
                <pre>
        //Show error message for RPC exceptions
        jQuery.Rpc.on('exception', function(event){
            $.jGrowl.error('ERROR: '+event.message);
        });                     
                </pre>
            </p>
        </div>
    </div>
    <div class="test">
            <p class="code"></p>
            <input type="text"></input>
            <button method_name="MainApi.func2">MainApi.func2</button>
            <p class="description">
                This method does not get any arguments. It just return Msg.
            </p>        
    </div>
    <script>
        function callback(response){
            $.jGrowl(response.toSource().slice(1,-1));
        };
        
        $('.test button').click(function(){
            var $this = $(this);
            var method_name = $this.attr('method_name');
            var args = $this.parent().find('input').val();
            if (args.length){
                var code = method_name+'('+args+', callback)';
            }else{
                var code = method_name+'(callback)';
            }
            $this.parent().find('.code').html(code);
            eval(code);
        })
    </script>
{% endblock %}